### ISSUE TITLE
Change submission procedure requiring a number which will conflict with other authors

### ISSUE THREAD

**Issue by freimuth82** [matuzo/HTMHell#24]
The current submission procedure is described as "Add a submission in ./hell/entries by copying any other markdown file in this folder. The filename should start with a counter followed by any file name, e.g. **12**_my_entry.md." - which will start to conflict when other authors try to merge their submissions like it already happened now with #22 and #23 where both authors (yeah, I am one of them ;) ) used number 7 as next entry. If the procedure will stay like this, there will be upcoming conflicts too. 

Maybe authors should not use numeric prefixes for their submissions but something else like a prefixed index for themselves like `authorprefix-index_my_entry.md` i.e. `f82-1_my_entry.md`?

**Comment by hacknug** [comment]
Maybe a GitHub Action could take care of fixing this? First opened/merged PR could take the first available spot. This could also save contributors from specifying a number since the Action would add it before/after merge.

**Comment by matuzo** [comment]
Thanks for suggestions.

The reason why I used it in the first place was to maintain correct order when multiple submissions where posted on the same date. Don't know why I didn't think about just adding the time like this `2019-10-22T01:00:00`. Anyways, that fixes the order issue.
