### ISSUE TITLE
Next/Previous Pagination on Entry

### ISSUE THREAD

**Issue by jevenson** [matuzo/HTMHell#42]
I think this is a great site! When browsing entries, I was wishing I had the ability to paginate though posts.

I went ahead and forked the repo, and I was able to get a next and previous button to show up on posts. I ran the `npm run screenshot` command, and those buttons are showing up in those screenshots.

I'll submit a PR and continue investigating the issue with the screenshots. Thanks for curating this list!

**Comment by jevenson** [comment]
I did figure it out! PR is ready to go

**Comment by matuzo** [comment]
Awesome, @jevenson, thank you.

I've tweeked the styling a bit, it's online now (#43) :)
