### ISSUE TITLE
Feed for new entries?

### ISSUE THREAD

**Issue by j9t** [matuzo/HTMHell#5]
It would be great if there was an RSS or Atom feed to follow additions to the site!

Feeling free to leave this suggestion as an issue unless this is already being worked on.

**Comment by matuzo** [comment]
Done! :)

Could you please validate that it works?
https://htmhell.netlify.com/feed.xml

Thanks!

**Comment by j9t** [comment]
Ha, awesome! That looks great! The W3C feed validator notes two issues [1] but the feed seems to be working fine.

Then, I’m subscribed but do you plan to add a `link` referencing the feed, or perhaps even a note on the feed?

[1] https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhtmhell.netlify.com%2Ffeed.xml

**Comment by matuzo** [comment]
Ah shit, I've posted the netlify link (edited now). This is the real link: https://htmhell.dev/feed.xml

I've fixed the warnings and added a link to the feed. Thanks, Jens!
