### ISSUE TITLE
Div type=button

### ISSUE THREAD

**Issue by k-sav** [matuzo/HTMHell#50]
Saw this one on a site for an Australian internet provider. 

```
<div type="button" ... >
 ...
</div>
```

Should this be it's own submission, or maybe just and addition to https://www.htmhell.dev/2-div-with-button-role/ ?

**Comment by matuzo** [comment]
Nice, thanks, but we've covered that already in <https://www.htmhell.dev/14-not-my-type/>.

If you find more, please share again. :)
