### ISSUE TITLE
Add EditorConfig for whitespace control

### ISSUE THREAD

**Issue by ndorfin** [matuzo/HTMHell#76]
Have you heard of [EditorConfig](https://editorconfig.org/)?

It's an editor plugin and config file that helps control whitespace and indenting for a project. It consists of:

1. An `.editorconfig` file (or set of files) that are added to the repo, with the rules for dealing with whitespace
2. A plugin that then works with your editor to stick to the rules set forth in the `.editorconfig` file described above

It unfortunately only works if each editor has the plugin installed. So it's not like a linting tool in that regard.

Anyway, If you're keen, I'll add the config file, and base its rules off your repo's current whitespace usage:

```
# EditorConfig is awesome: https://EditorConfig.org
# top-most EditorConfig file
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = false
insert_final_newline = true
```

- [x] Add `.editorconfig` file to the repo root
- [ ] Install EditorConfig plugin
- [x] Add an entry to the Readme about EditorConfig
- [ ] Questionable: Add a line about contributions using EditorCofnig ❓

**Comment by matuzo** [comment]
I guess now that the project is getting more popular, I should probably start working a bit cleaner haha. That's a great suggestion. It would be fantastic if you want to work on that. Thank you!

**Comment by ndorfin** [comment]
Cool thing. Done in #78  :)
